{
 "title": "Rocketmq_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "broker tps & broker qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_broker_tps" },
    { "expr": "rocketmq_broker_qps" }
   ]
  },
  {
   "title": "rocketmq_consumer_offset",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_offset" }
   ]
  },
  {
   "title": "rocketmq_consumer_message_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_message_size" }
   ]
  },
  {
   "title": "rocketmq_producer_offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_offset" }
   ]
  },
  {
   "title": "rocketmq_consumer_tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_tps" }
   ]
  },
  {
   "title": "rocketmq_producer_message_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_message_size" }
   ]
  },
  {
   "title": "rocketmq_producer_tps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_tps" }
   ]
  },
  {
   "title": "rocketmq_group_get_latency_by_storetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_group_get_latency_by_storetime"
    }
   ]
  },
  {
   "title": "rocketmq_message_accumulation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic)"
    }
   ]
  },
  {
   "title": "PutMessageDistributeTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_brokeruntime_pmdt_0ms" },
    {
     "expr": "rocketmq_brokeruntime_pmdt_0to10ms"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10to50ms"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_50to100ms"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_100to200ms"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_200to500ms"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_500to1s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_1to2s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_2to3s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_3to4s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_4to5s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_5to10s"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10stomore"
    }
   ]
  },
  {
   "title": "threadpoolqueue_headwait_timemills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills"
    },
    {
     "expr": "rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills"
    },
    {
     "expr": "rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills"
    }
   ]
  },
  {
   "title": "consume client info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_client_consume_fail_msg_count"
    },
    {
     "expr": "rocketmq_client_consume_fail_msg_tps"
    },
    {
     "expr": "rocketmq_client_consume_ok_msg_tps"
    },
    { "expr": "rocketmq_client_consume_rt" },
    {
     "expr": "rocketmq_client_consumer_pull_rt"
    },
    {
     "expr": "rocketmq_client_consumer_pull_tps"
    }
   ]
  },
  {
   "title": "runtime tps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_getfound_tps10"
    },
    {
     "expr": "rocketmq_brokeruntime_gettotal_tps10"
    },
    {
     "expr": "rocketmq_brokeruntime_gettransfered_tps10"
    },
    {
     "expr": "rocketmq_brokeruntime_getmiss_tps10"
    },
    {
     "expr": "rocketmq_brokeruntime_put_tps10"
    }
   ]
  },
  {
   "title": "disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_commitlog_disk_ratio"
    },
    {
     "expr": "rocketmq_brokeruntime_consumequeue_disk_ratio"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_free"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_total"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_maxoffset"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_minoffset"
    }
   ]
  },
  {
   "title": "broker runtime info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_msg_put_total_today_now"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_today_now"
    },
    {
     "expr": "rocketmq_brokeruntime_dispatch_behind_bytes"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_size_total"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_average_size"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_yesterdaymorning"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_yesterdaymorning"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_todaymorning"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_todaymorning"
    }
   ]
  }
 ]
}