apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: rocketmq-exporter
    namespace: monitoring
spec:
    namespaceSelector:
      matchNames:
      - monitoring
    podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: http
    selector:
      matchLabels:
        exporter: rocketmq-exporter