{
 "title": "Rocketmq_dashboard_new",
 "tags": [ "rocketmq" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "cluster", "query": "proRaftCluster,rcRaftCluster" },
   {
    "name": "env2",
    "label": "env2",
    "query": "label_values(rocketmq_broker_tps, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "broker tps & broker qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_broker_tps{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_broker_qps{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_offset",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_offset{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_message_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_message_size{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_offset{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_tps{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_message_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_message_size{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_tps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_tps{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_group_get_latency_by_storetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_group_get_latency_by_storetime{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "rocketmq_message_accumulation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset{cluster=\"$env\"}) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset{cluster=\"$env\"}) by (group,topic)"
    }
   ]
  },
  {
   "title": "PutMessageDistributeTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_pmdt_0ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_0to10ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10to50ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_50to100ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_100to200ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_200to500ms{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_500to1s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_1to2s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_2to3s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_3to4s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_4to5s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_5to10s{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10stomore{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "threadpoolqueue_headwait_timemills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "consume client info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_client_consume_fail_msg_count{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_client_consume_fail_msg_tps{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_client_consume_ok_msg_tps{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_client_consume_rt{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_client_consumer_pull_rt{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_client_consumer_pull_tps{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "runtime tps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_getfound_tps10{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_gettotal_tps10{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_gettransfered_tps10{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_getmiss_tps10{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_tps10{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_commitlog_disk_ratio{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_consumequeue_disk_ratio{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_free{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_total{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_maxoffset{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_minoffset{cluster=\"$env\"}"
    }
   ]
  },
  {
   "title": "broker runtime info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_msg_put_total_today_now{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_today_now{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_dispatch_behind_bytes{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_size_total{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_average_size{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_yesterdaymorning{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_yesterdaymorning{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_todaymorning{cluster=\"$env\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_todaymorning{cluster=\"$env\"}"
    }
   ]
  }
 ]
}