apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rocketmq
  labels:
    exporter: rocketmq-exporter
  annotations:
     kubernetes.io/change-cause: "init  dev rocketmq export"
  namespace: monitoring
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-exporter
  template:
    metadata:  
      labels:
        app: rocketmq-exporter
        exporter: rocketmq-exporter
    spec:
      containers:
      - name: test-rocketmq
        image: 192.168.0.134/exporter/rocketmq-exporter
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=512m"
        ports:
        - containerPort: 5557
          name: http
        args: ["${JAVA_OPTS}","--rocketmq.config.namesrvAddr='192.168.1.19:9876;192.168.0.101:9876;192.168.0.102:9876'","--rocketmq.config.rocketmqVersion=V4_8_0"]
        livenessProbe:
          tcpSocket:
            port: 5557
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 5557
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:        
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2000Mi