filebeat.shutdown_timeout: 1m
fields:
  filebeat-hostName: "INSTANCE-ID"
  filebeat-hostIp: "HOST_IP"
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access*.log
  fields:
    index: "nginx-access"
- type: log
  enabled: true
  json.keys_under_root: true   
  json.overwrite_keys: true
  json.add_error_key: true
  paths:
    - /var/log/nginx/error*.log
  fields:
    index: "nginx-error"

setup.template.settings:
  index.number_of_shards: 5
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  indices:
    - index: "nginx_access-%{+yyyy.MM.dd}"
      when.contains:
        fields:
          index: "nginx-access"
    - index: "nginx-error-%{+yyyy.MM.dd}"
      when.contains:
        fields:
          index: "nginx-error"