{
 "title": "Spring MVC 应用",
 "tags": [
  "App",
  "Java",
  "Spring",
  "MVC"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "App",
    "query": "label_values(http_server_requests_seconds_count,application)"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": "label_values(http_server_requests_seconds_count{application=\"$application\"},uri)"
   }
  ]
 },
 "panels": [
  { "title": "RED Method(Overview)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency(请求耗时)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", uri=~\"$uri\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Throughput(每秒请求数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 1d)) ",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 7d)) ",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Error(失败数)",
   "type": "graph",
   "description": "HTTP 请求状态为非 200 为请求处理失败。",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status!=\"200\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "description": "HTTP 请求状态为非 200 为请求处理失败。",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status=\"200\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  },
  { "title": "应用层", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "2XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",status=~\"2.*\"}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "3XX/4XX/5XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",status=~\"3.*\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",status=~\"4.*\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",status=~\"5.*\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "日志级别",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(increase(logback_events_total{application=\"$application\"}[1m])) by(level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Top 10(请求量)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "topk(10,sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[$__range])) by (uri))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "接口异常分布",
   "type": "grafana-piechart-panel",
   "description": "服务处理请求的时候内部报了异常，有时业务对于一些异常做了忽略，因此返回\b的 HTTP 状态还是 200，这时异常数和请求失败数的监控会有差别。",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",exception!=\"None\"}[$__range])) by (uri)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "接口异常实例分布",
   "type": "grafana-piechart-panel",
   "description": "服务处理请求的时候内部报了异常，有时业务对于一些异常做了忽略，因此返回\b的 HTTP 状态还是 200，这时异常数和请求失败数的监控会有差别。",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",exception!=\"None\"}[$__range])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "接口异常类型分布",
   "type": "grafana-piechart-panel",
   "description": "服务处理请求的时候内部报了异常，有时业务对于一些异常做了忽略，因此返回\b的 HTTP 状态还是 200，这时异常数和请求失败数的监控会有差别。",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\",exception!=\"None\"}[$__range])) by (exception)",
     "legendFormat": "{{expcetion}}"
    }
   ]
  }
 ]
}