{
 "title": "Spring MVC 接口",
 "tags": [
  "App",
  "Java",
  "Spring",
  "MVC",
  "Interface"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "App",
    "query": "label_values(jvm_memory_used_bytes,application)"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": "label_values(http_server_requests_seconds_count{application=\"$application\"},uri)"
   }
  ]
 },
 "panels": [
  { "title": "RED Method($uri)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "uri" },
  {
   "title": "Latency(请求耗时)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", uri=~\"$uri\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Throughput(每秒请求数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 1d)) ",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 7d)) ",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Error(失败数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status!=\"200\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status=\"200\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  },
  { "title": "RED Method($uri)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency(请求耗时)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri=~\"$uri\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", uri=~\"$uri\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Throughput(每秒请求数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 1d)) ",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",uri=~\"$uri\"}[1m] offset 7d)) ",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Error(失败数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status!=\"200\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\",status=\"200\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "now"
    }
   ]
  }
 ]
}