{
 "title": "Tomcat",
 "tags": [
  "Java",
  "Spring",
  "Tomcat"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(tomcat_threads_config_max_threads, application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tomcat_threads_config_max_threads{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Tomcat 单实例($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Throughput(每秒请求数)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_global_request_seconds_count{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "now"
    },
    {
     "expr": "rate(tomcat_global_request_seconds_count{instance=~\"$instance\", application=\"$application\"}[1m] offset 1d)",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "rate(tomcat_global_request_seconds_count{instance=~\"$instance\", application=\"$application\"}[1m] offset 7d)",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Latency(平均响应时间)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tomcat_global_request_seconds_sum{application=\"$application\", instance=~\"$instance\"}[1m]))/sum(rate(tomcat_global_request_seconds_count{application=\"$application\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "config max"
    },
    {
     "expr": "tomcat_threads_busy_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "busy"
    },
    {
     "expr": "tomcat_threads_current_threads{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_sessions_active_current_sessions{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "active"
    },
    {
     "expr": "rate(tomcat_sessions_expired_sessions_total{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "expired"
    },
    {
     "expr": "rate(tomcat_sessions_rejected_sessions_total{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_sent_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "now"
    },
    {
     "expr": "irate(tomcat_global_sent_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m] offset 1d)",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "irate(tomcat_global_sent_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m] offset 7d)",
     "legendFormat": "now - 7d"
    }
   ]
  },
  {
   "title": "Recieved Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(tomcat_global_received_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m])",
     "legendFormat": "now"
    },
    {
     "expr": "irate(tomcat_global_received_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m] offset 1d)",
     "legendFormat": "now - 1d"
    },
    {
     "expr": "irate(tomcat_global_received_bytes_total{instance=~\"$instance\", application=\"$application\"}[1m] offset 7d)",
     "legendFormat": "now - 7d"
    }
   ]
  }
 ]
}