apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    exporter: redis-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
    Selector:  app.kubernetes.io/name=node-exporter
spec:
  clusterIP: None
  selector:
    exporter: redis-exporter
  ports:
  - port: 9121
    targetPort: http
    name: http
---
piVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    exporter: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_container_name
      targetLabel: instance
    scheme: http
  jobLabel: redis-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      exporter: redis-exporter