apiVersion: v1
data:
  metersphere.properties: |-
    # 数据库配置
    spring.datasource.url=jdbc:mysql://x.x.x.x:3306/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=xxx
    spring.datasource.password=xxx
    # kafka 配置，node-controller 以及 data-streaming 服务需要使用 kafka 进行测试结果的收集和处理
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic=JMETER_METRICS
    kafka.test.topic=JMETER_TESTS
    kafka.bootstrap-servers=x.x.x.x:9092
    kafka.log.topic=JMETER_LOGS
    # node-controller 所使用的 jmeter 镜像版本 
    jmeter.image=registry.fit2cloud.com/metersphere/jmeter-master:0.0.6
    # 启动模式，lcoal 表示以本地开发模式启动
    #run.mode=local
    # CAS
    cas.client.name=MS_SERVER
    # CAS SERVER URL
    cas.server.url=http://xxx/cas
    # METERSPHERE SERVER URL
    cas.client.url=http://IP:8081
  ms-data-streaming.properties: |-
    ## DATABASE
    spring.datasource.url=jdbc:mysql://x.x.x.x:3306/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=root
    spring.datasource.password=F*84$6Yc9mYu1L2e
    ## KAFKA
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic=JMETER_TESTS
    kafka.bootstrap-servers=x.x.x.x:9092
    kafka.log.topic=JMETER_LOGS
    kafka.test.topic=JMETER_TESTS
    jmeter.report.granularity=5000
kind: ConfigMap
metadata:
  name: ms-properties
  namespace: ms
