apiVersion: v1
kind: Service
metadata:
  name: ms-node-controller-headless
  namespace: ms
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: ms-node-controller
  ports:
  - port: 8082
    targetPort: 8082
  
